#hibernate
#spring.jpa.hibernate.ddl-auto=update
#mysql
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=mysql://mysql.railway.internal:3306/SVC?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=mysql
#spring.datasource.hikari.connection-timeout=10000
#spring.datasource.hikari.maximum-pool-size=5
#server.port=8080#
server.port=${SERVER_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Para que no se cuelgue tanto
spring.datasource.hikari.connection-timeout=20000